### ISSUE TITLE
Can you provide some instructions about how to get the TableMe functional? 

### ISSUE THREAD

**Issue by PascalSun** [MaxKinny/TabRecSet#10]
Have tried and download the tableme.exe, however, it does not work.

After install the c++ build, pyqt-5, labelme, etc. 

It still says 

```
Traceback (most recent call last):
  File "labelme\main.py", line 193, in <module>
  File "labelme\main.py", line 176, in main
RuntimeError: super-class __init__() of type MainWindow was never called
[46340] Failed to execute script 'main' due to unhandled exception!
```

This tool obviously written in Python, can we also opensource it? 

Thank you!

**Comment by MaxKinny** [comment]
Please try:
1. After installing LabelMe, it is necessary to open it once.
2. Try to run the EXE in the Administrator mode.

**Comment by lytws** [comment]
> Please try:
> 
> 1. After installing LabelMe, it is necessary to open it once.
> 2. Try to run the EXE in the Administrator mode.

Hi @MaxKinny ,
I tried:
1. Created and activated a new conda environment in anaconda prompt running in the Administrator mode
2. Pip install labelme pyqt5
3. Start labelme
4. Start TableMe.exe

It still got the same issue. I also did it in conda base environment, which didn't work too.
Could you show me more details? 
Thank you!

**Comment by PascalSun** [comment]
> > Please try:
> 
> > 
> 
> > 1. After installing LabelMe, it is necessary to open it once.
> 
> > 2. Try to run the EXE in the Administrator mode.
> 
> 
> 
> Hi @MaxKinny ,
> 
> I tried:
> 
> 1. Created and activated a new conda environment in anaconda prompt running in the Administrator mode
> 
> 2. Pip install labelme pyqt5
> 
> 3. Start labelme
> 
> 4. Start TableMe.exe
> 
> 
> 
> It still got the same issue. I also did it in conda base environment, which didn't work too.
> 
> Could you show me more details? 
> 
> Thank you!

same here

**Comment by MaxKinny** [comment]
@PascalSun @lytws 
The software is expired. We release a one-week trial version. Please obtain it from our Figshare repo. We are pursuing the software copyright licences (https://github.com/MaxKinny/TabRecSet/issues/2#issuecomment-1493907352). Thank you for your understanding!

**Comment by MaxKinny** [comment]
@PascalSun @lytws Use this one-week trial version. The above problems may disappear.

**Comment by xiapengchng** [comment]
same question? Any update?

**Comment by MaxKinny** [comment]
> > Please try:
> > 
> > 1. After installing LabelMe, it is necessary to open it once.
> > 2. Try to run the EXE in the Administrator mode.
> 
> Hi [@MaxKinny](https://github.com/MaxKinny) , I tried:
> 
> 1. Created and activated a new conda environment in anaconda prompt running in the Administrator mode
> 2. Pip install labelme pyqt5
> 3. Start labelme
> 4. Start TableMe.exe
> 
> It still got the same issue. I also did it in conda base environment, which didn't work too. Could you show me more details? Thank you!

Sorry for the late reply. We have registered the software copyright for TableMe and released its fully functional version.

**Comment by MaxKinny** [comment]
> same question? Any update?

Sorry for the late reply. We have registered the software copyright for TableMe and released its fully functional version.
